/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.bonespirito.packageregistry

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test fun uuidReturnsTrue() {
        val classUnderTest = LogTracing()
        val uuid = classUnderTest.getUUID()
        assertTrue(uuid.isNotEmpty(), "UUID generated")
    }
}
